services:
  - type: web
    name: quantycs-api-docker
    env: docker
    dockerfilePath: ./Dockerfile.backend
    envVars:
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: quantycs-frontend-docker
    env: docker
    dockerfilePath: ./Dockerfile.frontend
    healthCheckPath: /
    autoDeploy: true 